### PR TITLE
Add unit tests for JobListing, JobListingWithFilter and JobPeriodSelector

### PR DESCRIPTION
**Pull request by mersanuzun**

### CODE REVIEW

**Comment by mersanuzun** [comment]
@abdullah Hi, again me :)

**Comment by fatihacet** [comment]
I will merge this right away because I am going to add Travis support.

@abdullah please review and comment. @mersanuzun can fix them later.

Thanks everyone 👍

**Comment by fatihacet** [comment]
For some reason, specs work fine on my local but they fail on Travis.

https://travis-ci.com/kodilan-com/frontend/builds/119699851

**Comment by abdullah** [comment]
@fatihacet The problem is that the node version is 8.16 - I've run test via 8.16 and gotten same errors.  v11.0.0 is fine.

**Comment by abdullah** [comment]
@mersanuzun I'll review ASAP :)

**Comment by fatihacet** [comment]
@abdullah thanks! I just updated the Node version on Travis config. Let's wait and see 🤞

**Comment by fatihacet** [comment]
Yeah! That worked 🎉 Thanks @abdullah 👍

**Comment by mersanuzun** [comment]
Ok, thank you @fatihacet and @abdullah . If any fix is needed, it will be done :)

**Pull request merged**
