### PR TITLE
Listing company logo fixed.

### PR DESCRIPTION
**Pull request by celepci**
At homepage listing company logos fixed.

### CODE REVIEW

**Comment by fatihacet** [comment]
@celepci can you add screenshots to your PR so we can see before and after changes?

**Comment by fatihacet** [comment]
@celepci also, thank you for contributing 👍

**Comment by celepci** [comment]
Of course. I forgot this. Sorry.

**Before**
image

**After**
image

**Comment by fatihacet** [comment]
Thanks @celepci 👍

**Pull request merged**
