### PR TITLE
Fix responsive some areas for mobile devices

### PR DESCRIPTION
**Pull request by erdoganbulut**

### CODE REVIEW

**Comment by fatihacet** [comment]
@erdoganbulut what does this PR fix? Can you add before and after screenshots?

**Comment by fatihacet** [comment]
@erdoganbulut I checked this in Chrome and on my iPhone and you did a really great job 👍 

I have a few feedbacks for you.

- The scroll to top icon is misaligned

image

- Font size of the input and selects are a bit bigger. I think it is 16px right now, we can try 14px. Also input and select placeholders don't line up properly. "Sehir seciniz" is a bit off to right.

image

- Since you did a lot of work on the redesign of the header, would you mind also fixing this one? https://github.com/kodilan-com/frontend/issues/8

Thanks 👍

**Comment by erdoganbulut** [comment]
Hello,

I am really sorry. I opened a little sloppy PR.

I'm adding screenshots.

Thank you for your kindness and compliment.

Before
Screenshot_2019-05-29 Kodilan com
After
Screenshot_2019-05-29 Kodilan com(1)
Before
Screenshot_2019-05-29 Screenshot
After
Screenshot_2019-05-29 Screenshot(2)
Before
Screenshot_2019-05-29 Senior Full-Stack Developer ( Net) Dekopasaj
After
Screenshot_2019-05-29 Senior Full-Stack Developer ( Net) Dekopasaj(1)
Before
Screenshot_2019-05-29 Screenshot(1)
After
Screenshot_2019-05-29 Screenshot(3)

**Comment by fatihacet** [comment]
@erdoganbulut thanks for the screenshots 👍

I left a few feedbacks to you. Would you mind taking a look at them?

So far really great work. Thanks 👍 😍

**Comment by erdoganbulut** [comment]
@fatihacet thanks for your feedbacks

i am interested in them 🙃

**Comment by erdoganbulut** [comment]
@fatihacet 

I didn't see aligment problem in the new post button. If the error persists; send browser, operating system, screenshot and page infos.

Backtotop button problem fixed: [Screenshot](https://user-images.githubusercontent.com/10667941/58552479-2bad0d00-821b-11e9-91c2-51b5f439ef5f.png)

Input and select text alignment problem fixed to general forms (and tested iPhone): [Screenshot](https://user-images.githubusercontent.com/10667941/58552479-2bad0d00-821b-11e9-91c2-51b5f439ef5f.png)

**Comment by fatihacet** [comment]
@erdoganbulut 

Chrome 74 on macOS Mojave

- ✅1200px

>

- ❌ 900px



- ❌ 700px



- ✅450px

**Comment by fatihacet** [comment]
I will merge this as is because this improves current UI a lot. @erdoganbulut feel free to create another PR for https://github.com/kodilan-com/frontend/pull/10#issuecomment-496944954.

Thanks you for contributing to kodilan. It will look much better 👍

**Pull request merged**
