### PR TITLE
'JobPosting' schema markup added for improving SEO

### PR DESCRIPTION
**Pull request by TugayYaldiz**
https://jobs.google.com/about/

Google iş ilanlarında zengin sonuçlar için gerekli markup eklendi
image

Örnek iş ilanı:
https://kodilan.com/ilanlar/alkosoft-bilisim-senior-unreal-engine-vr-game-developer

Sonuç:
kodilan

Not: Code-İnput yazan yerler Google'ın koyduğu dummy text oralarda kodilan.com olacak.

### CODE REVIEW

**Comment by fatihacet** [comment]
@TugayYaldiz how can I test this?

**Comment by gokaygurcan** [comment]
@fatihacet 

https://search.google.com/structured-data/testing-tool > CODE SNIPPET

**Comment by TugayYaldiz** [comment]
Thanks @gokaygurcan. @fatihacet also here https://search.google.com/test/rich-results we can only test as code snippet since site not published with this code yet. Pasting all HTML code with these microdata will be enough for testing.

**Comment by fatihacet** [comment]
Thanks @gokaygurcan and @TugayYaldiz. I verify that this change helps our SEO efforts 👍 

image

**Pull request merged**
